# 用户token 抓包获取
token: '88D0F74F-F54C-4DE4-A91F-A1D3D4DD9134'
#163的邮箱
sender: '13054511186@163.com'
#邮箱服务器
mail_host: "smtp.163.com"
#邮箱用户名
mail_user: "13054511186@163.com"
#邮箱密钥
mail_pass: "JHMODUBIERVVCFLO"
#接收人
receivers:
        - 1010158370@qq.com